# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.2.4

# Cache settings: Set to true to enable caching
cache: false

# File strategy s3/firebase
# fileStrategy: "s3"

# Custom interface configuration
interface:
  customWelcome: "Oi {{user.name}}"
  # Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://xablau.com/privacy'
    openNewTab: true

  # Terms of service
  termsOfService:
    externalUrl: 'https://xablau.com/tos'
    openNewTab: true
    modalAcceptance: true
    modalTitle: "Termos e Condições"
    modalContent: |
       #Termos de Serviço da Plataforma de Chat com IA
     

        1. Licença de Uso do Código do Painel de Administração

        Ao adquirir um pacote específico que inclua essa funcionalidade, você recebe uma licença limitada para baixar e utilizar o código-fonte fornecido, exclusivamente para acessar um painel de administração relacionado à Plataforma. Embora você tenha o direito de usar este código conforme licenciado, fica expressamente proibida a revenda, redistribuição, sublicenciamento ou qualquer outra forma de transferência deste código para terceiros sem nossa permissão prévia e explícita por escrito. A titularidade e os direitos de propriedade intelectual sobre o código permanecem conosco ou com nossos licenciadores.

        2. Coleta e Uso de Dados Pessoais

        Para fornecer e aprimorar nossos Serviços, processar transações e manter a comunicação com você, coletamos dados pessoais como nome, endereço de e-mail e informações de pagamento. A forma como coletamos, usamos e protegemos seus dados está detalhada em nossa Política de Privacidade, a qual recomendamos a leitura atenta.

        3. Cookies e Tecnologias Semelhantes

        Nossa Plataforma utiliza cookies e outras tecnologias similares para melhorar a sua experiência de usuário, analisar o tráfego e o uso dos Serviços, e habilitar certas funcionalidades. Ao continuar a usar a Plataforma, você concorda com o uso de cookies de acordo com as práticas descritas em nossa Política de Privacidade.

        4. Conduta do Usuário e Uso Aceitável

        Você concorda em utilizar a Plataforma apenas para fins lícitos e de forma a não violar leis, regulamentos ou os direitos de terceiros. É proibido usar os Serviços de maneira que possa restringir ou inibir o uso e aproveitamento da Plataforma por outros usuários. Comportamentos inadequados incluem, mas não se limitam a: assédio, envio de conteúdo ofensivo, obsceno ou ilegal, ou qualquer ação que interrompa ou prejudique o funcionamento normal dos Serviços.

        5. Legislação Aplicável

        Estes Termos serão regidos e interpretados de acordo com as leis da jurisdição aplicável onde nossa entidade está registrada, sem consideração a conflitos de princípios legais que possam direcionar a aplicação da lei de outra jurisdição.

        6. Alterações nos Termos

        Reservamo-nos o direito de modificar estes Termos a qualquer momento, a nosso exclusivo critério. Notificaremos os usuários sobre quaisquer alterações significativas através do endereço de e-mail fornecido ou por meio de um aviso destacado na Plataforma. O uso continuado da Plataforma após a notificação e publicação das alterações constituirá sua aceitação tácita dos Termos revisados.

        7. Contato

        Se você tiver alguma dúvida ou precisar de esclarecimentos sobre estes Termos de Serviço, por favor, entre em contato conosco através dos canais de comunicação oficiais indicados em nossa Plataforma.

        Aceitação dos Termos

        Ao utilizar a Plataforma de Chat com IA, você reconhece que leu, compreendeu e concorda em cumprir estes Termos de Serviço.    


  endpointsMenu: true
  modelSelect: true
  parameters: false
  sidePanel: true
  presets: false
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: false
  runCode: false

# Example Registration Object Structure (optional)
#registration:
  #socialLogins: ['github', 'google', 'discord', 'openid', 'facebook', 'apple']
  # allowedDomains:
  # - "gmail.com"


balance:
  enabled: true
  startBalance: 20000
  autoRefillEnabled: true
  refillIntervalValue: 10
  refillIntervalUnit: 'minutes'
  refillAmount: 50000

speech:
  tts:
    openai:      
      apiKey: '${TTS_API_KEY}'
      model: 'gpt-4o-mini-tts'
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']


  stt:
    openai:      
      apiKey: '${STT_API_KEY}'
      model: 'whisper-1'


rateLimits:
  fileUploads:
    ipMax: 50
    ipWindowInMinutes: 60
    userMax: 50
    userWindowInMinutes: 60
  conversationsImport:
    ipMax: 50
    ipWindowInMinutes: 60
    userMax: 50
    userWindowInMinutes: 60
  stt:
    ipMax: 50
    ipWindowInMinutes: 1
    userMax: 50
    userWindowInMinutes: 1
  tts:
    ipMax: 50
    ipWindowInMinutes: 1
    userMax: 50
    userWindowInMinutes: 1

# Example Actions Object Structure
# actions:
#   allowedDomains:
#     - "swapi.dev"
#     - "librechat.ai"
#     - "google.com"

# Example MCP Servers Object Structure
# mcpServers:
#   everything:
#     # type: sse # type can optionally be omitted
#     url: http://localhost:3001/sse
#     timeout: 60000  # 1 minute timeout for this server, this is the default timeout for MCP servers.
#   puppeteer:
#     type: stdio
#     command: npx
#     args:
#       - -y
#       - "@modelcontextprotocol/server-puppeteer"
#     timeout: 300000  # 5 minutes timeout for this server
#   filesystem:
#     # type: stdio
#     command: npx
#     args:
#       - -y
#       - "@modelcontextprotocol/server-filesystem"
#       - /home/user/LibreChat/
#     iconPath: /home/user/LibreChat/client/public/assets/logo.svg
#   mcp-obsidian:
#     command: npx
#     args:
#       - -y
#       - "mcp-obsidian"
#       - /path/to/obsidian/vault

# Definition of custom endpoints
endpoints:
  # assistants:
  #   disableBuilder: false # Disable Assistants Builder Interface by setting to `true`
  #   pollIntervalMs: 3000  # Polling interval for checking assistant updates
  #   timeoutMs: 180000  # Timeout for assistant operations
  #   # Should only be one or the other, either `supportedIds` or `excludedIds`
  #   supportedIds: ["asst_supportedAssistantId1", "asst_supportedAssistantId2"]
  #   # excludedIds: ["asst_excludedAssistantId"]
  #   # Only show assistants that the user created or that were created externally (e.g. in Assistants playground).
  #   # privateAssistants: false # Does not work with `supportedIds` or `excludedIds`
  #   # (optional) Models that support retrieval, will default to latest known OpenAI models that support the feature
  #   retrievalModels: ["gpt-4-turbo-preview"]
  #   # (optional) Assistant Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
  #   capabilities: ["code_interpreter", "retrieval", "actions", "tools", "image_vision"]
  # agents:
  #   # (optional) Default recursion depth for agents, defaults to 25
  #   recursionLimit: 50
  #   # (optional) Max recursion depth for agents, defaults to 25
  #   maxRecursionLimit: 100
  #   # (optional) Disable the builder interface for agents
  #   disableBuilder: false
  #   # (optional) Agent Capabilities available to all users. Omit the ones you wish to exclude. Defaults to list below.
  #   capabilities: ["execute_code", "file_search", "actions", "tools"]
  custom:
    - name: 'IA'      
      apiKey: '${OPENROUTER_KEY}'
      baseURL: 'https://openrouter.ai/api/v1'
      models:
        default: ['meta-llama/llama-3-70b-instruct']
        fetch: true
      titleConvo: true
      titleModel: 'meta-llama/llama-3-70b-instruct'
      dropParams: ['stop']
      modelDisplayLabel: 'IA'        
    
    - name: 'Free models'      
      apiKey: '${OPENROUTER_KEY}'
      baseURL: 'https://openrouter.ai/api/v1'
      models:
        default: 
        - allenai/molmo-7b-d:free
        - bytedance-research/ui-tars-72b:free
        - cognitivecomputations/dolphin3.0-mistral-24b:free
        - cognitivecomputations/dolphin3.0-r1-mistral-24b:free
        - deepseek/deepseek-chat-v3-0324:free
        - deepseek/deepseek-chat:free
        - deepseek/deepseek-r1-distill-llama-70b:free
        - deepseek/deepseek-r1-distill-qwen-14b:free
        - deepseek/deepseek-r1-distill-qwen-32b:free
        - deepseek/deepseek-r1-zero:free
        - deepseek/deepseek-r1:free
        - deepseek/deepseek-v3-base:free
        - featherless/qwerky-72b:free
        - google/gemini-2.0-flash-exp:free
        - google/gemini-2.0-flash-thinking-exp-1219:free
        - google/gemini-2.0-flash-thinking-exp:free
        - google/gemini-2.5-pro-exp-03-25:free
        - google/gemma-2-9b-it:free
        - google/gemma-3-12b-it:free
        - google/gemma-3-1b-it:free
        - google/gemma-3-27b-it:free
        - google/gemma-3-4b-it:free
        - google/learnlm-1.5-pro-experimental:free
        - huggingfaceh4/zephyr-7b-beta:free
        - meta-llama/llama-3.1-8b-instruct:free
        - meta-llama/llama-3.2-11b-vision-instruct:free
        - meta-llama/llama-3.2-1b-instruct:free
        - meta-llama/llama-3.2-3b-instruct:free
        - meta-llama/llama-3.3-70b-instruct:free
        - meta-llama/llama-4-maverick:free
        - meta-llama/llama-4-scout:free
        - mistralai/mistral-7b-instruct:free
        - mistralai/mistral-nemo:free
        - mistralai/mistral-small-24b-instruct-2501:free
        - mistralai/mistral-small-3.1-24b-instruct:free
        - moonshotai/kimi-vl-a3b-thinking:free
        - moonshotai/moonlight-16b-a3b-instruct:free
        - nousresearch/deephermes-3-llama-3-8b-preview:free
        - nvidia/llama-3.1-nemotron-70b-instruct:free
        - nvidia/llama-3.1-nemotron-nano-8b-v1:free
        - nvidia/llama-3.1-nemotron-ultra-253b-v1:free
        - nvidia/llama-3.3-nemotron-super-49b-v1:free
        - open-r1/olympiccoder-32b:free
        - open-r1/olympiccoder-7b:free
        - qwen/qwen-2.5-72b-instruct:free
        - qwen/qwen-2.5-7b-instruct:free
        - qwen/qwen-2.5-coder-32b-instruct:free
        - qwen/qwen-2.5-vl-7b-instruct:free
        - qwen/qwen2.5-vl-32b-instruct:free
        - qwen/qwen2.5-vl-3b-instruct:free
        - qwen/qwen2.5-vl-72b-instruct:free
        - qwen/qwq-32b-preview:free
        - qwen/qwq-32b:free
        - rekaai/reka-flash-3:free
        - sophosympatheia/rogue-rose-103b-v0.2:free
        - openrouter/auto
        fetch: false
      titleConvo: true
      titleModel: 'meta-llama/llama-3-70b-instruct'
      dropParams: ['stop']      

    - name: 'AIs'
      apikey: 'dummy'
      baseURL: ${PORTKEY_GATEWAY_URL}
      headers:
        x-portkey-api-key: '${PORTKEY_API_KEY}'
        x-portkey-config: 'pc-chatai-7fe96e'
      models:
        default: ['llama-3.2']
        fetch: true
      titleConvo: true
      titleModel: "current_model"
      summarize: false
      summaryModel: "current_model"
      forcePrompt: false
      modelDisplayLabel: "Gateway"
      iconURL: https://images.crunchbase.com/image/upload/c_pad,f_auto,q_auto:eco,dpr_1/rjqy7ghvjoiu4cd1xjbf

fileConfig:
  endpoints:    
    default:
      fileLimit: 4
      fileSizeLimit: 10  
      totalSizeLimit: 50 
      supportedMimeTypes:    
      - "text/x-c"
      - "text/x-c\\+\\+"      
      - "text/html"
      - "text/x-java"      
      - "text/markdown"
      - "application/pdf"
      - "text/x-php"      
      - "text/javascript"
      - "text/x-python"
      - "text/x-script.python"
      - "text/x-ruby"
      - "text/x-tex"
      - "text/plain"
      - "text/css"      
      - "text/vtt"
      - "image/jpeg"      
      - "image/gif"
      - "image/png"
      - "image/svg"
      - "image/svg+xml"
      - "application/csv"
      - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      - "application/json"
      - "application/vnd.openxmlformats-officedocument.presentationml.presentation"
      - "application/typescript"
      - "application/xml"      
      - "application/vnd.ms-excel"
      - "application/msexcel"
      - "application/x-msexcel"
      - "application/x-ms-excel"
      - "application/x-excel"
      - "application/x-dos_ms_excel"
      - "application/xls"
      - "application/x-xls"
      - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      - "text/csv"
      - "text/comma-separated-values"
      - "text/x-comma-separated-values"
      - "text/tab-separated-values"
      - "text/x-csv"
  serverFileSizeLimit: 100  # Global server file size limit in MB
  avatarSizeLimit: 2  # Limit for user avatar image size in MB
